version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/nullpointer
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend/nullpointer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nullpointer_db
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nullpointer_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
  
volumes:
  pgdata:

networks:
  mynetwork: